changelog:
  categories:
    - title: "⚠️ Breaking Changes"
      labels:
        - "breaking change"
    - title: "🚀 Enhancements"
      labels:
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
    - title: "Other Changes"
      labels:
        - "*"
